ansible_user: Administrator
ansible_password: administrator_password
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_port: 5985
ansible_winrm_scheme: http
# ansible_winrm_port: 5986
# ansible_winrm_scheme: https


# OUS:
#   - OUS_variable
# OUS_variable:
#   - name: test
#     path: 